### ISSUE TITLE
common.py throws a FutureWarning from bleak call to get_discovered_devices

### ISSUE THREAD

**Issue by MrYsLab** [adafruit/Adafruit_Blinka_bleio#41] opened 2022-04-03 20:10 UTC
When calling the [bleak scanner method](https://github.com/adafruit/Adafruit_Blinka_bleio/blob/a7d037244956a2d77e99250f76c11f9660d46386/_bleio/common.py#L362), **_get_discovered_devices_**, a [future warning is thrown](https://github.com/hbldh/bleak/blob/6c38e8711aceda32fb4d4765d83a24508793f811/bleak/backends/scanner.py#L196).
Please update by using the bleak **_discovered_devices_** property as suggested in the warning.

**Comment by MrYsLab** [comment] 2022-04-04 18:25
@tekktrik, I must be missing something. I don't see any changes to common.py or a separate branch. Could you please explain why this issue is closed if there are no changes? Thanks.

**Comment by tekktrik** [comment] 2022-04-04 18:40
Hi @MrYsLab, the issue is still open, I just had opened a PR for this issue because I thought it would be simpler than it was.  Right now we're pinning our version of `bleak` so we'd need to re-pin in to a more updated version I believe.  I've left the issue open in that case.

**Comment by tekktrik** [comment] 2022-04-19 13:43
@makermelissa is there any plan or benefit to upgrading `bleak` at some point?  That would allow for resolving this issue.

**Closed** 2023-04-03 17:33 UTC
